# PBS configuration
# If submitting to a different project to your default uncomment line below 
# and change project code as appropriate
# project: w35
queue: express
walltime: 0:30:00
jobname: 1deg_jra55_ryf
ncpus: 132
mem: 500GB

# Force payu to always find, and save, files in this short (or scratch) project directory
# shortpath: /scratch/w35

# Model configuration
name: common
model: access-om2
input: /g/data4/ik11/inputs/access-om2/input_rc/common_1deg_jra55
submodels:
    - name: atmosphere
      model: yatm
      exe: /scratch/fp0/pcl900/access-om2/access-om2-gadi-scaling/bin/yatm_a9e2883-modified.exe
      input: 
            - /g/data4/ik11/inputs/access-om2/input_rc/yatm_1deg
            - /g/data1a/ua8/JRA55-do/RYF/v1-3/
      ncpus: 1

    - name: ocean
      model: mom
      exe: /scratch/fp0/pcl900/access-om2/access-om2-gadi-scaling/bin/fms_ACCESS-OM_4a2f211-modified_libaccessom2_a9e2883-modified.x
      input: /g/data4/ik11/inputs/access-om2/input_rc/mom_1deg
      ncpus: 107

    - name: ice
      model: cice5
      exe: /scratch/fp0/pcl900/access-om2/access-om2-gadi-scaling/bin/cice_auscom_360x300_24p_365bdc1-modified_libaccessom2_a9e2883-modified.exe
      input: /g/data4/ik11/inputs/access-om2/input_rc/cice_1deg
      ncpus: 24

# Collation
collate:
  walltime: 1:00:00
  mem: 30GB
  ncpus: 4
  queue: express
  exe: /g/data4/ik11/inputs/access-om2/bin/mppnccombine

# Misc
runlog: true
stacksize: unlimited
qsub_flags: -lother=hyperthread -W umask=027
# set number of cores per node (28 for normalbw, 48 for normal on gadi)
platform:
    nodesize: 48

# DANGER! Do not uncomment this without checking the script is synching 
# to the correct location!
# postscript: sync_output_to_gdata.sh
