# PBS configuration
queue: normal
project: fp0
walltime: 2:00:00
jobname: 1deg_jra55_ryf
ncpus: 288
mem: 500GB
shortpath: /scratch/fp0

# Model configuration
name: common
model: access-om2
input:       /g/data/fp0/pcl900/input_236a3011/common_1deg_jra55
submodels:
    - name: atmosphere
      model: yatm
      exe: /scratch/fp0/pcl900/access-om2-gadi/bin/yatm_2cc76e2-modified.exe
      input: /g/data/fp0/pcl900/input_236a3011/yatm_1deg
      ncpus: 1

    - name: ocean
      model: mom
      exe: /scratch/fp0/pcl900/access-om2-gadi/bin/fms_ACCESS-OM_46774ee-modified_libaccessom2_2cc76e2-modified.x
      input: /g/data/fp0/pcl900/input_236a3011/mom_1deg
      ncpus: 216

    - name: ice
      model: cice5
      exe: /scratch/fp0/pcl900/access-om2-gadi/bin/cice_auscom_360x300_24p_dd02b01-modified_libaccessom2_2cc76e2-modified.exe
      input: /g/data/fp0/pcl900/input_236a3011/cice_1deg
      ncpus: 24

# Collation
collate:
  walltime: 1:00:00
  mem: 30GB
  ncpus: 4
  queue: express
  exe: /g/data/fp0/pcl900/bin/mppnccombine

# Misc
runlog: True
stacksize: unlimited
mpirun: --mca orte_base_help_aggregate 0
qsub_flags: -V -lstorage=scratch/fp0+gdata/fp0 -lother=hyperthread -W umask=027
platform:
    nodesize: 48
# postscript: sync_output_to_gdata.sh
